urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 12 22:23:09 2019

@author: Tamuz
"""

from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<str:url>', views.post_detail, name='post_detail'),
    path('failure/', views.failure, name='failure'),
    path('secure_post_detail/<str:url>', views.secure_post_detail, name='secure_post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('writers/', views.post_writers, name='post_writers'),
    path('post/<pk>/publish', views.post_publish, name='post_publish'),
    path('post/<pk>/remove', views.post_remove, name='post_remove'),
    path('post/<str:url>/comment', views.add_comment_to_post, name='add_comment_to_post'),
    path('post/<str:PostUrl>/<int:CommentPk>/comment', views.add_comment_to_comment, name='add_comment_to_comment'),
    path('comment/<int:pk>/approve', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove', views.comment_remove, name='comment_remove'),
    path('phrase/<int:pk>/edit', views.phrase_edit, name='phrase_edit'),
    path('phrase/<int:pk>/new', views.phrase_new, name='phrase_new'),
    
    path('subscribed/', views.subscribed_view, name='subscribed_view'),
    path('subscribed_success/', views.subscribed_success, name='subscribed_success'),


]

templates/blog/add_comment_to_post.html
{% extends 'tour/base.html' %}
{% load static %}


{% block head %}
        <title>קיימברידג' בעברית הבלוג</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <script src="https://www.google.com/recaptcha/api.js?render={{reCAPTCHA_site_key}}"></script>
<script>
   grecaptcha.ready(function() {
      grecaptcha.execute('{{reCAPTCHA_site_key}}', {action: "/add_comment_to_post/"}).then(function(token) {
        document.getElementById('g-recaptcha-response').value = token;
      });
  });
  
 </script>
        
    {% endblock %}
{% block content %}
   
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-center ">
        <div class="col-sm-12 col-md-10 col-lg-3 runner">
     
            {% include 'blog/blog_side_bar.html' %}
                
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
    
        <div class="col-sm-12 col-md-8 col-lg-4 post_main">
                <div class="col-12 blog_name">
                    <h3>הוספת תגובה</h3>
                </div>
            <div class="col-12">
                <h1><a href="{% url 'blog:post_new' %}" class="top-menu"><i class="fas fa-edit"></i>תגובה חדשה</a></h1>
            </div>
            <form method="POST" class="post-form">{% csrf_token %}
                    
                {{ form.as_p }}
                
                <input type="hidden" name="g-recaptcha-response" id='g-recaptcha-response'>
                <button type="submit" class="btn btn-runner">שלח</button>
            </form>
        
            </div> <!-- "row "  -->     
          </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Close previous div -->
        </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
    </div><!-- container-fluid -->
<!--- Welcome Section -->

{% endblock %}

templates/blog/blog_side_bar.html
{% load static %}
<!--

    <div class="row">
        <div class="title2" >
            בלוגים לפי נושאים
        </div>
    </div>
    <div class="row ">
        <hr class="light">
    </div>
-->
<!-- 
    <li class="nav-item "><a class="nav-link" href="">משימות</a></li>
-->
    
<ul class="nav nav_blog flex-column flex-nowrap">
    <li class="nav-item "><a class="nav-link" href="{% url 'blog:post_list' %}">פוסטים אחרונים</a></li>
    {% if user.is_authenticated %}
    <li class="nav-item "><a class="nav-link" href="{% url 'blog:post_draft_list' %}">טיוטות</a></li>
    {% endif %}
    <li class="nav-item "><a class="nav-link" href="{% url 'blog:post_writers' %}">על הכותבים</a></li>
    {% for post in latest_posts %}
    <li class="nav-item "><a class="nav-link" href="{% url 'blog:post_detail' url=post.url %}"><img width="20%" src="{{post.image.url}}"/> {{post.title}}</a></li>
    
    {% endfor %}

</ul>
<!-- 
<div class="row ">
    <hr class="light">
    <div class="col-sm-12 col-md-12 col-lg-12"> 
        <div class="blog_name">
            <h6>רוצים לשמוע עוד על החוויות שלנו?
</h6><h6>
הצטרפו לרשימה
            </h6>
        </div>
    </div>
    <div class="space"></div>
    <div class="col-sm-12 col-md-12 col-lg-8"> 
        <form method="POST" action = "{% url 'blog:subscribed_view' %}" >{% csrf_token %}
        {{ subscribedForm.as_p }}
        <button type="submit" class="save btn btn-blog">אשמח לקרוא</button>
        </form>
    </div>
</div>
-->

templates/blog/failure.html
{% extends 'tour/base.html' %}
{% load static %}
{% load blog_extras %}

{% block facebook_event %}
        fbq('track', 'ViewContent');
{% endblock %}
	

{% block content %}

<div class="jumbotron row d-flex  justify-content-center text-right ">
    <div class="col-sm-12 col-md-3 col-lg-3 runner order-1 order-lg-0">
 
            {% include 'blog/blog_side_bar.html'  %}
        
    </div><!-- col-md-3 col-lg-4 disapear_sm runner -->

    
    <div class="col-sm-12 col-md-8 col-lg-8 post_main order-0 order-lg-1">
    
        <div class="row main_text">
            <div class="col-sm-12 col-md-12 col-lg-8">
      <h3>לצערנו אירעה תקלה</h3>
      
      <p> אנא נסה שוב במידה והתקלה מופיעה שוב, שלח הודעה בצור קשר ונשוב אליך בהקדם</p>
      <p> הצלחת לעשות לוג אין אבל כנראה שהתאריך עבר...</p>
      <hr>
     
      <p class="lead">
        <a class="btn btn-primary btn-sm" href="{% url  'tour:home'  %}" role="button">בחזרה לדף הבית</a>
        <a class="btn btn-primary btn-sm" href="{% url  'logout'  %}" role="button"> Logout </a>
      </p>
      
    </div>
  </div>
</div>
</div>
{% endblock %}

templates/blog/phrase_edit.html
{% extends 'tour/base.html' %}
{% load static %}
{% block head %}
       <link rel="stylesheet" href="{% static 'css/blog.css' %}">
       <a href="{% url 'blog:post_new' %}" class="top-menu"><i class="fas fa-edit"></i></a>
       
    {% endblock %}
{% block content %}
   
              
          
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-center ">
        <div class="col-sm-12 col-md-10 col-lg-3 runner">
     
            <div class="row">
                <hr class="light">
            </div>
            <div class="row">
                  <div class="title2">
     המלצות
                  </div>
    
            </div>
            
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
    
        
        <div class="col-sm-12 col-md-12 col-lg-8">
            <div class="jumbotron row d-flex  justify-content-center text-center ">
                <div class="row main_text">
                    <div class="col-12">
                        <h1><a href="{% url 'blog:post_new' %}" class="top-menu"><i class="fas fa-edit"></i>פוסט חדש</a></h1>
                    </div>
                </div>
            </div>
            <div class="row main_text">

                <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-blog">שמור</button>
                  </form>




               <hr class="short">
                 </div> <!-- "row main_text"  -->     
              </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Our tours row -->

          
            
<!--- Close previous div -->
        </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
    </div><!-- container-fluid -->
<!--- Welcome Section -->

{% endblock %}

templates/blog/post_detail.html
{% extends 'tour/base.html' %}
{% load static %}
{% load blog_extras %}

{% block facebook_event %}
        fbq('track', 'ViewContent');
{% endblock %}

{% block content %}
          
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-right ">
        <div class="col-sm-12 col-md-3 col-lg-3 runner order-1 order-lg-0">
     
                {% include 'blog/blog_side_bar.html'  %}
            
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
    
        
        <div class="col-sm-12 col-md-8 col-lg-8 post_main order-0 order-lg-1">
        
            <div class="row main_text">
                <div class="col-sm-12 col-md-12 col-lg-8">
                      {% if user.is_authenticated %}

                      {% for group in user.groups.all %}
                          {% if group.name == 'blog_admin' %}
                            

                    <!--
                        
                        <div class="col-12">
                        -->
                        <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><i class="fas fa-edit"></i></a>

                        <!--
                        <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><i class="fas fa-trash"></i></a>
                        </div>
                    -->
                    {% endif %}
                    {% endfor %}

                    {% endif %}
                    <div class="blog_name">
                        <h2>{{ post.title }}</h2>
                        <hr>
                    </div>
                    <!--
                        <div class="col-12">
                        -->
                        {% if post.published_date %}
                        <div class="text-right mb-2"><i><b>{{ post.published_date|date:"d.m.Y" }}</b></i></div>
                        <!--
                       
                        <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
                         -->
                        {% endif %}
                        <!--
                        </div>
                    -->
                    <!--
                        <div class="col-8"><p>
                        -->
                        
                        <a class="phrase_img" href="#" data-image-id="" data-toggle="modal" data-title=""
                        data-image="{{post.image.url}}"
                        data-target="#image-post">
                        <img class="img-thumbnail"
                        src="{{post.image.url}}"
                        alt="">
                    </a>
                    <!--
                    </div>
                -->
                
                
                <!--
                    <div class="col-12">
                    -->
                    {{ post.text |blog_url_and_linebreaks }}
                    <!--
                    </div>
                -->
        
        
                </div> <!-- "col-sm-12 col-md-12 col-lg-8"  -->     
            </div> <!-- "row main_text"  -->     
            
            
                {% for phrase in post.phrases.all %}

                    {% if user.is_authenticated %}

                    {% for group in user.groups.all %}
                    {% if group.name == 'blog_admin' %}
                      

                    <div class="col-12">
                            <a class="btn btn-default" href="{% url 'blog:phrase_edit' pk=phrase.pk %}"><i class="fas fa-edit"></i>ערוך פסקה תחתונה</a>
                            <!--<a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><i class="fas fa-trash"></i></a>-->
                        </div>
              {% endif %}
              {% endfor %}
                   
                    {% endif %}
                    {% if phrase.title %}
                    <div class="col-12 blog_name">
                        <h3>{{ phrase.title }}</h3>
                    </div>
                    {% endif %}
                
                    {% if phrase.text1 %}
                    <div class="col-12">

                        {% if phrase.text1_html_style is True %}
                            {{ phrase.text1 |safe}}
                        {% else %}
                            {{ phrase.text1 |blog_url_and_linebreaks }}
                        {% endif %}
                    </div>
                    {% endif %}

                    <div class="row">
                        {% if phrase.image.url is not null %}
                            {% if phrase.num_images == '1' %}
                                <div class="col-sm-12 col-md-12 col-lg-8">
                            {% elif phrase.num_images == '2' %}
                                <div class="col-sm-12 col-md-6 col-lg-6">
                            {% else %}
                                <div class="col-sm-12 col-md-4 col-lg-4">
                            {% endif %}
                        

                            <a class="phrase_img" href="#" data-image-id="" data-toggle="modal" data-title=""
                            data-image="{{phrase.image.url}}"
                            data-target="#image-post">
                            <img class="img-thumbnail"
                                src="{{phrase.image.url}}"
                                alt="">
                            </a>
                            {% if phrase.image_sub %}
                                <div class="blog_subtext">
                                    {{ phrase.image_sub |safe}}
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}

                        {% if phrase.image2.url is not null %}
                        {% if phrase.num_images == '1' %}
                        <div class="col-sm-12 col-md-12 col-lg-8">
                    {% elif phrase.num_images == '2' %}
                        <div class="col-sm-12 col-md-6 col-lg-6">
                    {% else %}
                        <div class="col-sm-12 col-md-4 col-lg-4">
                    {% endif %}
                            <a class="phrase_img" href="#" data-image-id="" data-toggle="modal" data-title=""
                        data-image="{{phrase.image2.url}}"
                        data-target="#image-post">
                        <img class="img-thumbnail"
                            src="{{phrase.image2.url}}"
                            alt="">
                    </a>
                    {% if phrase.image2_sub %}
                    <div class="blog_subtext">
                        {{ phrase.image2_sub }}
                    </div>
                {% endif %}
                    </div>
                    {% endif %}

                    {% if phrase.image3.url is not null %}
                    {% if phrase.num_images == '1' %}
                    <div class="col-sm-12 col-md-12 col-lg-8">
                {% elif phrase.num_images == '2' %}
                    <div class="col-sm-12 col-md-6 col-lg-6">
                {% else %}
                    <div class="col-sm-12 col-md-4 col-lg-4">
                {% endif %}
                        <a class="phrase_img" href="#" data-image-id="" data-toggle="modal" data-title=""
                    data-image="{{phrase.image3.url}}"
                    data-target="#image-post">
                    <img class="img-thumbnail"
                        src="{{phrase.image3.url}}"
                        alt="">
                    </a>
                    {% if phrase.image3_sub %}
                    <div class="blog_subtext">
                        {{ phrase.image3_sub }}
                    </div>
                {% endif %}
                    </div>
                  {% endif %}
                </div>
                <div class="pharse_space"></div>
                    
                {% endfor %}
                {% if user.is_authenticated %}

                {% for group in user.groups.all %}
                {% if group.name == 'blog_admin' %}
                  
                <a class="btn btn-default" href="{% url 'blog:phrase_new' pk=post.pk %}"><i class="fas fa-edit"></i>הוסף פסקה חדשה</a>

                {% endif %}
                {% endfor %}

                
                {% endif %}
                
            <hr>
            {% if ShowComments %}
            <div class="row main_text">
                <a class="btn btn-runner" href="{% url 'blog:add_comment_to_post' url=post.url %}"> הוסף תגובה לכתבה</a>
            {% for comment in post.comments.all %}
                {% if user.is_superuser or comment.approved_comment %}
                
                <div class="col-12">
                        <strong>{{ comment.author }}</strong>
                    {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><i class="fas fa-trash"></i></a>
                    <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><i class="fa fa-check"></i></a>
                    {% endif %}
                    <div class="comment_space">

                        <div class="date">{{ comment.created_date|date:"d.m.Y" }}</div>
                        {{ comment.text |blog_url_and_linebreaks }}
                    </div>
                </div>
                    {% for subComment in comment.subComments.all %}
                        {% if user.is_superuser or subComment.approved_comment %}

                            <div class="col-12 subcomment">
                                <strong>{{ subComment.author }}</strong>
                                {% if not subComment.approved_comment %}
                                    <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=subComment.pk %}"><i class="fas fa-trash"></i></a>
                                    <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=subComment.pk %}"><i class="fa fa-check"></i></a>
                                {% endif %}
                                    <div class="comment_space">
    
                                        <div class="date">{{ subComment.created_date|date:"d.m.Y" }}</div>
                                        {{ subComment.text |blog_url_and_linebreaks }}
                                    </div>
                            </div>
                        {% endif %}


                    {% endfor %}
                    <a class="btn deafult" href="{% url 'blog:add_comment_to_comment' PostUrl=post.url CommentPk=comment.pk %}">הגב</a>

                {% endif %}
    {% endfor %}
            </div>
            {% endif %}

        </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Our tours row -->

          
            
<!--- Close previous div -->
    </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
</div><!-- container-fluid -->
<!--- Welcome Section -->

{% endblock %}

templates/blog/post_draft_list.html
{% extends 'tour/base.html' %}
{% load static %}
{% block head %}
        <title>Cambridge In Hebrew blog</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    {% endblock %}
{% block content %}
   
              
          
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-center ">
        <div class="col-sm-12 col-md-10 col-lg-3 runner">
     
            <div class="row">
                <hr class="light">
            </div>
            <div class="row">
                  <div class="title2">
     המלצות
                  </div>
    
            </div>
            
            
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
    
        
        <div class="col-sm-12 col-md-12 col-lg-8">
        <div class="jumbotron row d-flex  justify-content-center text-center ">
            <div class="row main_text">
                <div class="col-12">
                <h1><a href="#">טיוטה</a></h1>
                </div>
                </div>
                </div>
                <div class="row main_text">
        {% for post in posts %}
                <div class="col-12">
                    <div class="text-left mb-2"><i><b>created:{{ post.created_date|date:"d.m.Y" }}</b></i></div>
                     </div>
                     
                     <div class="col-12">
                            <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
                    </div>
                     <div class="col-12">
                    <p>{{ post.text|truncatechars:200 }}</p>
                    </div>
        
        
           
        
        {% endfor %}
        
           <hr class="short">
            </div> <!-- "row main_text"  -->     
          </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Our tours row -->

          
            
<!--- Close previous div -->
        </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
    </div><!-- container-fluid -->
<!--- Welcome Section -->

    





{% endblock %}

templates/blog/post_edit.html
{% extends 'tour/base.html' %}
{% load static %}
{% block head %}
       <link rel="stylesheet" href="{% static 'css/blog.css' %}">
       <a href="{% url 'blog:post_new' %}" class="top-menu"><i class="fas fa-edit"></i></a>
       
    {% endblock %}
{% block content %}
   
              
          
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-center ">
        <div class="col-sm-12 col-md-10 col-lg-3 runner">
     
            <div class="row">
                <hr class="light">
            </div>
            <div class="row">
                  <div class="title2">
     המלצות
                  </div>
    
            </div>
            
            
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
    
        
        <div class="col-sm-12 col-md-12 col-lg-8">
            <div class="jumbotron row d-flex  justify-content-center text-center ">
                <div class="row main_text">
                    <div class="col-12">
                        <h1><a href="{% url 'blog:post_new' %}" class="top-menu"><i class="fas fa-edit"></i>פוסט חדש</a></h1>
                    </div>
                </div>
            </div>
            <div class="row main_text">
                <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-blog">שמור</button>
                </form>
        
               <hr class="short">
                 </div> <!-- "row main_text"  -->     
              </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Our tours row -->

          
            
<!--- Close previous div -->
        </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
    </div><!-- container-fluid -->
<!--- Welcome Section -->

    





{% endblock %}

templates/blog/post_list.html
{% extends 'tour/base.html' %}
{% load static %}
{% load blog_extras %}

{% block content %}
   
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-center ">
        <div class="col-sm-12 col-md-3 col-lg-3 runner order-1 order-lg-0">
     
            {% include 'blog/blog_side_bar.html' %}
                
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
    
        <div class="col-sm-12 col-md-8 col-lg-8 post_main order-0 order-lg-1">

            <div class="col-12 blog_name">
                <h1><a href="#">{{page_title}}</a></h1>
            </div>
            <div class="row ">
                {% if user.is_authenticated %}
                {% for group in user.groups.all %}
                {% if group.name == 'blog_admin' %}
                  
                <div class="col-12">
                        <a class="btn btn-default" href="{% url 'blog:post_new' %}"><i class="far fa-plus-square"></i></a>
                    </div>
                {% endif %}
                {% endfor %}




                {% endif %}
           
                {% for post_even_or_odd in posts %}
                <div class="col-sm-12 col-md-6">
                    {% for post in post_even_or_odd %}

                    <div class="row post_column">

                <div class="col-12 blog_name text-right">
                        <h3><a href="{% url 'blog:post_detail' url=post.url %}">{{ post.title }}</a></h3>
                    </div>
                    {% if post.published_date %}
                    <div class="col-12 text-right mb-2"><i><b>{{ post.published_date|date:"d.m.Y" }}</b></i></div>
                    {% endif %}
                    {% if post.image %}
                    <div class="col-12">
                        <a class="post_img" href="#" data-image-id="" data-toggle="modal" data-title=""
                        data-image="{{post.image.url}}"
                        data-target="#image-post">
                        <img class="img-thumbnail"
                        src="{{post.image.url}}"
                        alt="">
                    </a>
                    </div>
                {% endif %}

                <div class="col-12">
                {{ post.text |blog_url_and_linebreaks }}
                </div>
                <!--

                    <div class="col-12">
                        <a href="{% url 'blog:post_detail' url=post.url %}">מספר תגובות: {{ post.approved_comments.count }}</a>
                    </div>
                -->
                    </div> <!-- "row post_column"  --> 
                
                    {% endfor %}
                </div> <!-- "col-sm-12 col-md-6"  --> 
                {% endfor %}  
        
        
            </div> <!-- "row "  -->     
          </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Close previous div -->
        </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
    </div><!-- container-fluid -->
<!--- Welcome Section -->

{% endblock %}

templates/blog/post_new.html
{% extends 'tour/base.html' %}
{% block head %}
   
<a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
 {% endblock %}
{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/blog/subscribed.html
{% extends 'tour/base.html' %}
{% load static %}


{% block head %}
        <title>קיימברידג' בעברית הבלוג</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    {% endblock %}
{% block content %}
   
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-center ">
        <div class="col-sm-12 col-md-10 col-lg-3 runner">
     
            {% include 'blog/blog_side_bar.html' %}
                
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
    
        <div class="col-sm-12 col-md-8 col-lg-4 post_main">
            <div class="col-12 blog_name">
                <h1><a href="#">{{page_title}}</a></h1>
            </div>
            <form method="POST" class="post-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Send</button>
                </form>
        
            </div> <!-- "row "  -->     
          </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Close previous div -->
        </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
    </div><!-- container-fluid -->
<!--- Welcome Section -->

{% endblock %}

templates/blog/subscribed_success.html
{% extends 'tour/base.html' %}
{% load static %}

fbq('track', 'Lead');
{% block facebook_event %}
        fbq('track', 'Lead');
{% endblock %}
{% block content %}
   
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-center ">
        <div class="col-sm-12 col-md-10 col-lg-3 runner">
     
            {% include 'blog/blog_side_bar.html' %}
                
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
        
        <div class="col-sm-12 col-md-12 col-lg-8 post_main">
            <div class="col-12 blog_name">
                <h1><a href="#">{{page_title}}</a></h1>
            </div>
            <div class="row ">
                
                <div class="col-12">
                    <p>
                        תודה שנרשמתם, נשלח מייל אישור ברגעים אלו
                    </p>
                    <p class="lead">
                        <a class="btn btn-runner" href="{% url  'blog:post_list'  %}" role="button">בחזרה לרשימת הפוסטים</a>
                    </p>        
                </div>
            </div> <!-- "row post_column"  --> 
        </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Close previous div -->
        </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
    </div><!-- container-fluid -->
<!--- Welcome Section -->

{% endblock %}

templates/blog/tasks.html
{% extends 'tour/base.html' %}
{% load static %}
{% block head %}
        <title>Cambridge In Hebrew blog</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    {% endblock %}
{% block content %}
   
              
          
<div class="container-fluid">
   
<!--- Jumbotron -->
    <div class="jumbotron row d-flex  justify-content-center text-center ">
        <div class="col-sm-12 col-md-10 col-lg-3 runner">
     
            {% include 'blog/blog_side_bar.html' %}
            
        </div><!-- col-md-3 col-lg-4 disapear_sm runner -->
    
        
        <div class="col-sm-12 col-md-12 col-lg-8">
        <div class="jumbotron row d-flex  justify-content-center text-center ">
            <div class="row main_text">
                <div class="col-12">
                <h1><a href="#">משימות</a></h1>
                </div>
                </div>
                </div>
                <div class="row main_text">
        {% for subscribed in SubscribedList %}
        <tr class="data">
        <td>{{  subscribed.id }}</td>
        <td>{{  subscribed.first_name }}</td>
        <td>{{  subscribed.email }}</td>
        <td><a href="{% url  'tour:subscribed_confirm' entry.id True %}" class="btn btn-tour reg-btn">לא ספאם</a></td>
        <td><a href="{% url  'tour:subscribed_confirm' entry.id False %}" class="btn btn-tour reg-btn">ספאם</a></td>
        
        </tr>
           
        
        {% endfor %}
        
           <hr class="short">
            </div> <!-- "row main_text"  -->     
          </div>  <!-- col-sm-12 col-md-12 col-lg-8 -->             
          
<!--- Our tours row -->

          
            
<!--- Close previous div -->
        </div><!-- jumbotron row  text-center .d-none .d-sm-block -->
    </div><!-- container-fluid -->
<!--- Welcome Section -->

    





{% endblock %}